repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: https://gitee.com/kcrist/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ["--max-line-length=120", "--ignore=B008,W503"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # check for security issues in Python code
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.4
#    hooks:
#      - id: bandit
#        args: [--severity-level, medium]
