version: '3.4'

services:
  consul:
    image: hashicorp/consul
    networks:
      - deepagenix
    ports:
      - "${CONSUL_PORT}:8500"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    volumes:
      - ./appdata/consul:/consul/data

  postgres:
    image: postgres
    networks:
      - deepagenix
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data

  nginx:
    image: deepagenix-nginx-upsync
    networks:
      - deepagenix
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./appdata/nginx/conf.d:/usr/local/nginx/conf.d
      - ./appdata/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./appdata/nginx/upstreams:/usr/local/nginx/conf/servers
      - ./web/dist:/var/www/frontend
    depends_on:
      - main

  elasticsearh:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./appdata/elasticsearch/data:/usr/share/elasticsearch/data
      - ./appdata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./appdata/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      #- "9301:9300"

  main:
    image: deepagenix-main
    networks:
      - deepagenix
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    volumes:
      - ./appdata/knowledge:/app/knowledge
    depends_on:
      - consul
      - postgres

  component-python:
    image: deepagenix-component-python
    networks:
      - deepagenix
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - main

networks:
  deepagenix:
    driver: bridge