version: '3.4'

services:
  consul:
    image: hashicorp/consul
    networks:
      - deepagenix
    ports:
      - "${CONSUL_PORT}:${CONSUL_PORT}"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    volumes:
      - ./appdata/consul:/consul/data

  nginx:
    image: nginx-upsync
    networks:
      - deepagenix
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./appdata/nginx/conf.d:/usr/local/nginx/conf.d
      - ./appdata/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./appdata/nginx/upstreams:/usr/local/nginx/conf/servers
      - ./web/dist:/var/www/frontend
    depends_on:
      - core
      - component-python

  core:
    image: deepagenix-core
    networks:
      - deepagenix
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    ports:
      - "8080"
    depends_on:
      - consul

  component-python:
    image: deepagenix-component-python
    networks:
      - deepagenix
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    ports:
      - "8000"
    depends_on:
      - core

networks:
  deepagenix:
    driver: bridge