Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Information

Postgres:
  Host: localhost
  Port: 5433
  User: postgres
  Password: postgres
  Database: deepagenix

RagIndex:
  Elasticsearch:
    Url: http://localhost:9201
    Password: 