database:
  user: dev_user
  password: dev_password
  name: ai_platform_dev
  host: localhos
  pool_size: 5

cache:
  type: redis
  redis:
    host: localhost
    port: 6379
    db: 0

logging:
  level: DEBUG

security:
  secret_key: insecure_dev_secret
