Logging:
  LogLevel:
    Default: Warning
    Microsoft.AspNetCore: Warning

Postgres:
  Host: postgres
  Port: 5432
  User: postgres
  Password: postgres
  Database: deepagenix

RagIndex:
  Elasticsearch:
    Url: http://elasticsearch:9200
    Password: 